### PR TITLE
Add PoolConnection import from cuttlepool

### PR DESCRIPTION
**Pull request by lucasw-99**
Hello smitchell556!  I'm not sure if you can tell, but this is my very first submitted pull request on GitHub.  Although I realize the edit I made is likely not exactly what you wanted, I'd love to work on this project further with you.  If you give me more context on what your error is, I believe I would be able to contribute to this project.

I apologize for asking you to put more effort into describing this problem when you likely already know what the issue is, but please help if you can!  I'm somewhat new to GitHub and very interested in contributing to open source, so my first accepted pull request would be a huge milestone.  Thanks for reading, I hope you give me feedback :)

Lucas

### CODE REVIEW

**Comment by smitchell556** [comment]
That's exactly what I was looking for. Very simple fix. I just noticed when I was creating some tests that I needed to import that class and that it would improve uniformity and simplicity if I could import it directly from `flask_cuttlepool.py` instead of the python package that this one wraps.

Thank you!

PS. Sorry for the late response. I don't know why I wasn't notified when the pull request was made. I'll look into my notification settings.

**Comment by lww515** [comment]
Of course, thanks for letting me contribute 👍 If there are any more open issues with cuttlepool, I would love to work on them as well, as I hope this isn't the last pull request that I make on your project if that's fine with you 😄

**Comment by smitchell556** [comment]
You can always watch the repository by clicking the "Watch" button in the top right corner (next to the "Star" and "Fork" buttons). Then any time a new issue is added, you should be notified.

Thanks again!

**Comment by smitchell556** [comment]
Hey @lww515 if you are interested, there is another issue for the dependency of this project that you may want to take a look at smitchell556/cuttlepool#33.

**Comment by lww515** [comment]
Hey @smitchell556 , I am definitely interested!  I have school during the week so I'll likely get to looking at it more seriously over the weekend.  Thank you for keeping me in mind though, I'd love to contribute to your project again and I hope me waiting until the weekend isn't an issue 😊

**Pull request merged**
